server:
  port: 8080
spring:
  application:
    name: ddd-demo-service

  # datasource
  datasource:
    url: jdbc:h2:mem:demo;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS "public";
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
